//! Thin wrapper around the `git` binary — same approach as TS implementation.
//! Using subprocess keeps dependencies minimal and matches what the user sees
//! when they cd into the project root.

use crate::error::{AppError, AppResult};
use std::path::{Path, PathBuf};
use tokio::fs;
use tokio::process::Command;

async fn git(cwd: &Path, args: &[&str]) -> AppResult<String> {
    let out = Command::new("git")
        .args(args)
        .current_dir(cwd)
        .output()
        .await
        .map_err(|e| AppError::Git(format!("spawn git: {e}")))?;
    if !out.status.success() {
        return Err(AppError::Git(format!(
            "git {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr)
        )));
    }
    Ok(String::from_utf8_lossy(&out.stdout).to_string())
}

pub async fn ensure_repo(root: &Path, name: &str, idea: &str) -> AppResult<()> {
    fs::create_dir_all(root).await?;
    if root.join(".git").exists() {
        return Ok(());
    }
    git(root, &["init", "-b", "main"]).await?;
    git(root, &["config", "user.email", "autonomych@local"]).await?;
    git(root, &["config", "user.name", "Autonomych"]).await?;
    fs::write(
        root.join("README.md"),
        format!("# {name}\n\n{idea}\n\nGenerated by Autonomych.\n"),
    )
    .await?;
    fs::write(
        root.join(".gitignore"),
        "node_modules/\ndist/\nbuild/\n.env\n.env.local\n*.log\n.DS_Store\n",
    )
    .await?;
    git(root, &["add", "."]).await?;
    git(root, &["commit", "-m", "chore: initial commit"]).await?;
    Ok(())
}

pub async fn create_worktree(root: &Path, branch: &str, worktree_path: &Path) -> AppResult<()> {
    let branches = git(root, &["branch", "--list"]).await.unwrap_or_default();
    let wt_str = worktree_path.to_string_lossy().into_owned();
    if !branches.contains(branch) {
        git(
            root,
            &["worktree", "add", "-b", branch, &wt_str, "main"],
        )
        .await?;
    } else {
        git(root, &["worktree", "add", &wt_str, branch]).await?;
    }
    Ok(())
}

pub async fn remove_worktree(root: &Path, worktree_path: &Path) -> AppResult<()> {
    let wt_str = worktree_path.to_string_lossy().into_owned();
    let _ = git(root, &["worktree", "remove", "--force", &wt_str]).await;
    Ok(())
}

pub async fn commit_all(worktree: &Path, message: &str) -> AppResult<bool> {
    let status = git(worktree, &["status", "--porcelain"]).await?;
    if status.trim().is_empty() {
        return Ok(false);
    }
    git(worktree, &["add", "-A"]).await?;
    git(worktree, &["commit", "-m", message]).await?;
    Ok(true)
}

#[derive(Debug)]
pub struct MergeResult {
    pub ok: bool,
    pub conflict: bool,
    pub message: String,
}

pub async fn merge_branch(root: &Path, branch: &str) -> MergeResult {
    let out = Command::new("git")
        .args(["merge", "--no-ff", "--no-edit", branch])
        .current_dir(root)
        .output()
        .await;
    match out {
        Ok(o) if o.status.success() => MergeResult {
            ok: true,
            conflict: false,
            message: String::from_utf8_lossy(&o.stdout).to_string(),
        },
        Ok(o) => {
            let msg = format!(
                "{}{}",
                String::from_utf8_lossy(&o.stdout),
                String::from_utf8_lossy(&o.stderr),
            );
            let conflict = msg.contains("CONFLICT");
            if conflict {
                let _ = Command::new("git")
                    .args(["merge", "--abort"])
                    .current_dir(root)
                    .output()
                    .await;
            }
            MergeResult { ok: false, conflict, message: msg }
        }
        Err(e) => MergeResult {
            ok: false,
            conflict: false,
            message: format!("spawn git: {e}"),
        },
    }
}

pub async fn tag(root: &Path, name: &str) -> AppResult<()> {
    let _ = git(root, &["tag", "-f", name]).await;
    Ok(())
}

pub async fn delete_branch(root: &Path, branch: &str) -> AppResult<()> {
    let _ = git(root, &["branch", "-D", branch]).await;
    Ok(())
}

/// Wipe all orphan worktrees + autonomych/iter-* branches. Mirror of TS
/// cleanup.ts.
pub async fn cleanup_orphan_worktrees(root: &Path) -> AppResult<usize> {
    let wt_dir = root.join(".autonomych").join("worktrees");
    if !wt_dir.exists() {
        return Ok(0);
    }
    let mut entries = match fs::read_dir(&wt_dir).await {
        Ok(e) => e,
        Err(_) => return Ok(0),
    };
    let mut removed = 0;
    while let Ok(Some(entry)) = entries.next_entry().await {
        let path: PathBuf = entry.path();
        let _ = Command::new("git")
            .args(["worktree", "remove", "--force"])
            .arg(&path)
            .current_dir(root)
            .output()
            .await;
        let _ = fs::remove_dir_all(&path).await;
        removed += 1;
    }
    let _ = Command::new("git")
        .args(["worktree", "prune"])
        .current_dir(root)
        .output()
        .await;
    if let Ok(out) = git(root, &["branch", "--list", "autonomych/iter-*"]).await {
        for line in out.lines() {
            let b = line.trim_start_matches(['*', ' ']).trim();
            if !b.is_empty() {
                let _ = git(root, &["branch", "-D", b]).await;
            }
        }
    }
    Ok(removed)
}
